use_frameworks!

platform :ios, '9.0'

target 'SFCategory_Example' do
  pod 'SFCategory', :path => '../'

  target 'SFCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
